package com.incture.utility;


import java.io.FileNotFoundException;
import java.util.Properties;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import org.springframework.stereotype.Service;

@Service
public class SendMailTLS {

	public static  String main(String toMail,String vendorId) throws FileNotFoundException {
		final String username = "akula.veerraju@incture.com";
		final String password = "Raju@123";

		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		if(!username.contains("gmail.com"))
			props.put("mail.smtp.host", "smtp.office365.com");  //if sender uses microsoft mail
		else
			props.put("mail.smtp.host", "smtp.gmail.com");     //if sender using gmail.com
		props.put("mail.smtp.port", "587");

		Session session = Session.getInstance(props,
				new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		});

		try {

			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress(username));     //senders id address
			message.setRecipients(Message.RecipientType.TO,
					InternetAddress.parse(toMail));    //to id address

			message.setSubject("Vendor creation");

			Multipart multipart = new MimeMultipart();
			BodyPart messageBodyPart = new MimeBodyPart();   //1st object
			String s1="https://webidetesting0539315-af91a028a.dispatcher.hana.ondemand.com/webapp/index.html?hc_orionpath=%2FDI_webide_di_workspaces7pc0ak54widfhdr%2FvendorManagement&neo-di-affinity=BIGipServerdisapwebide.hana.ondemand.com+%21JcgRA79x%2FRhGYP8d5jKFI7F71MsHquARExkG2Yr2MUYc12fnfVzrlsKvuclNaWl3rUFOXXRnuTHDEvU%3D&origional-url=index.html&sap-ui-appCacheBuster=..%2F&sap-ui-xx-componentPreload=off?vendorId="+vendorId;
			String s2="This is Autogenerated e-mail and may contain confidential or privileged information for the intended recipient (s). If you are not the intended recipient, please do not use or disseminate the information, notify the sender and delete it permanently.";
			messageBodyPart.setText(s1+"\n \n"+ s2+" \n \n");
			multipart.addBodyPart(messageBodyPart);  

			// Send the complete message parts
			message.setContent(multipart);
			Transport.send(message);
			System.err.println("done");
			return "Mail sent";
		} catch (MessagingException e) {
			return "error while sending mail:- "+e.getMessage();

		}
	}

}